/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface CloudflareImagesBinding {
  input(stream: ReadableStream): {
    transform(options: Record<string, unknown>): {
      output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
    };
  };
}

interface Env {
  ASSETS: Fetcher;
  IMAGES?: CloudflareImagesBinding;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/_vinext/image") {
      // allowedWidths ไม่ส่ง (undefined) เพื่อให้รับทุก width ที่ component ร้องขอได้
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: env.IMAGES
          ? async (body, { width, format, quality }) => {
              const result = await env.IMAGES!.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
              return result.response();
            }
          : undefined,
      });
    }

    return handler.fetch(request);
  },
};
